<?php
namespace Redaxscript;

$language = Language::getInstance();
$element = new Html\Element();
$setElement = $element
	->copy()
	->init('div',
	[
		'class' => $admin ? 'rs-admin-set-accordion' : 'rs-set-accordion'
	]);
$inputElement = $element
	->copy()
	->init('input',
	[
		'class' => $admin ? 'rs-admin-fn-status-accordion' : 'rs-fn-status-accordion',
		'type' => 'checkbox'
	]);
$labelElement = $element
	->copy()
	->init('label',
	[
		'class' => $admin ? 'rs-admin-fn-toggle-accordion rs-admin-label-accordion' : 'rs-fn-toggle-accordion rs-label-accordion'
	]);
$boxElement = $element
	->copy()
	->init('div',
	[
		'class' => $admin ? 'rs-admin-fn-accordion rs-admin-box-accordion' : 'rs-fn-accordion rs-box-accordion'
	]);
?>

<!-- accordion -->

<div class="<?php echo $admin ? 'rs-admin-component-accordion' : 'rs-component-accordion'; ?>">

	<?php for ($i = 1; $i < 6; $i++): ?>

		<?php echo $setElement
				->copy()
				->html(
					$inputElement
						->copy()
						->attr('id', $admin ? 'Modules\Preview\Admin\\' . $i : 'Modules\Preview\\' . $i)
						->attr('checked', $i === 1 ? 'checked' : null)
						->text($language->get($i, '_number')) .
					$labelElement
						->copy()
						->attr('for', $admin ? 'Modules\Preview\Admin\\' . $i : 'Modules\Preview\\' . $i)
						->text($language->get($i, '_number')) .
					$boxElement
						->copy()
						->text($language->get($i, '_number'))
		); ?>

	<?php endfor; ?>

</div>
