<?php
namespace Redaxscript;

$language = Language::getInstance();
$element = new Html\Element();
$tableElement = $element
	->copy()
	->init('table',
	[
		'class' => $admin ? 'rs-admin-table-default' : 'rs-table-default'
	]);
$theadElement = $element->copy()->init('thead');
$tfootElement = $element->copy()->init('tfoot');
$tbodyElement = $element->copy()->init('tbody');
$captionElement = $element->copy()->init('caption');
$thElement = $element->copy()->init('th');
$tdElement = $element->copy()->init('td');
$outputHead = null;
$outputFoot = null;
$outputBody = null;
?>

<!-- content -->

<?php for ($i = 1; $i < 6; $i++): ?>

	<?php $outputHead .= $thElement
		->copy()
		->addClass($admin ? 'rs-admin-is-size-1of5' : 'rs-is-size1of5')
		->text($language->get($i, '_number')); ?>

	<?php $outputFoot .= $tdElement
		->text($language->get($i, '_number')); ?>

	<?php $outputBody .= $tdElement
		->text($language->get('preview', '_preview')); ?>

<?php endfor; ?>

<!-- table -->

<div class="<?php echo $admin ? 'rs-admin-wrapper-table' : 'rs-wrapper-table'; ?>">

	<?php echo $tableElement->html(
		$theadElement->html('<tr>' . $outputHead . '</tr>') .
		$tbodyElement->html(
			'<tr>' . $outputBody . '</tr>' .
			'<tr>' . $outputBody . '</tr>' .
			'<tr>' . $outputBody . '</tr>'
		) .
        $tfootElement->html('<tr>' . $outputFoot . '</tr>')
	); ?>

</div>

<!-- table with caption -->

<div class="<?php echo $admin ? 'rs-admin-wrapper-table' : 'rs-wrapper-table'; ?>">

	<?php echo $tableElement->html(
		$captionElement->text('Caption') .
		$tbodyElement->html(
			'<tr>' . $outputBody . '</tr>' .
			'<tr>' . $outputBody . '</tr>' .
			'<tr>' . $outputBody . '</tr>'
		)
	); ?>

</div>
