<?php namespace Redaxscript\Template; ?>

<!-- main -->

<main id="main" class="rs-main">

	<!-- teaser -->

	<?php if (!Tag::getRegistry('adminParameter')): ?>
		<?php include('default/helper/teaser.php'); ?>
		<?php echo $teaser; ?>
	<?php endif; ?>

	<!-- error -->

	<?php if (Tag::getRegistry('contentError')): ?>
		<div class="rs-wrapper rs-wrapper-page">
			<?php echo Tag::partial('default/error.phtml'); ?>
		</div>

	<!-- else content and sidebar -->

	<?php else: ?>
		<div class="rs-wrapper rs-wrapper-page rs-has-sidebar">
			<?php echo Tag::partial(
			[
				'default/content.phtml',
				'default/sidebar.phtml'
			]); ?>
		</div>
	<?php endif; ?>

</main>